import 'package:flutter/widgets.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:my_app/models/todo.dart';
import '../repositories/todo_repositories.dart';
import './todo_provider.dart';

part 'todo_controller.g.dart';

/// TodoController manages the state and operations for todos.
/// It extends _$TodoController which is auto-generated by riverpod_annotation.
@riverpod
class TodoController extends _$TodoController {
  // Runs automatically when provider starts
  @override
  Future<List<Todo>> build() async {
    final repo = ref.read(todoRepositoryProvider);
    return repo.getTodos();
  }

  /// Add a new todo to the list
  Future<void> addTodo(Todo todo) async {
    final repo = ref.read(todoRepositoryProvider);

    await repo.createTodo(todo);

    state = const AsyncLoading();

    state = AsyncData(await repo.getTodos());
  }

  /// Delete a todo by its ID
  Future<void> deleteTodo(String id) async {
    final repo = ref.read(todoRepositoryProvider);

    await repo.delete(id);

    final current = state.value ?? [];

    state = AsyncData(current.where((t) => t.id != id).toList());
  }

  /// Toggle the completion status of a todo
  Future<void> toggleTodo(String id, bool value) async {
    final repo = ref.read(todoRepositoryProvider);

    final current = state.value ?? [];

    final index = current.indexWhere((t) => t.id == id);

    if (index == -1) return;

    final updated = [...current];

    updated[index].completed = value;

    await repo.updateTodo(id, updated[index]);

    state = AsyncData(updated);
  }

  /// Update an existing todo with new values
  Future<void> updateTodo(String id, Todo todo) async {
    final repo = ref.read(todoRepositoryProvider);

    await repo.updateTodo(id, todo);

    final current = state.value ?? [];

    final index = current.indexWhere((t) => t.id == id);

    if (index == -1) return;

    final updated = [...current];
    updated[index] = todo;

    state = AsyncData(updated);
  }
}
