// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'todo_controller.dart';

// **************************************************************************
// RiverpodGenerator
// **************************************************************************

// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, type=warning
/// TodoController manages the state and operations for todos.
/// It extends _$TodoController which is auto-generated by riverpod_annotation.

@ProviderFor(TodoController)
final todoControllerProvider = TodoControllerProvider._();

/// TodoController manages the state and operations for todos.
/// It extends _$TodoController which is auto-generated by riverpod_annotation.
final class TodoControllerProvider
    extends $AsyncNotifierProvider<TodoController, List<Todo>> {
  /// TodoController manages the state and operations for todos.
  /// It extends _$TodoController which is auto-generated by riverpod_annotation.
  TodoControllerProvider._()
    : super(
        from: null,
        argument: null,
        retry: null,
        name: r'todoControllerProvider',
        isAutoDispose: true,
        dependencies: null,
        $allTransitiveDependencies: null,
      );

  @override
  String debugGetCreateSourceHash() => _$todoControllerHash();

  @$internal
  @override
  TodoController create() => TodoController();
}

String _$todoControllerHash() => r'919c449fb1eaf3b523e4fee5ce296c50ef23a3d3';

/// TodoController manages the state and operations for todos.
/// It extends _$TodoController which is auto-generated by riverpod_annotation.

abstract class _$TodoController extends $AsyncNotifier<List<Todo>> {
  FutureOr<List<Todo>> build();
  @$mustCallSuper
  @override
  void runBuild() {
    final ref = this.ref as $Ref<AsyncValue<List<Todo>>, List<Todo>>;
    final element =
        ref.element
            as $ClassProviderElement<
              AnyNotifier<AsyncValue<List<Todo>>, List<Todo>>,
              AsyncValue<List<Todo>>,
              Object?,
              Object?
            >;
    element.handleCreate(ref, build);
  }
}
